# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_soup": "00_scraping.ipynb"}

modules = ["core/scraping.py"]

doc_url = "https://calicorob.github.io/czapi/"

git_url = "https://github.com/calicorob/czapi/tree/master/"

def custom_doc_links(name): return None
