# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_constants.ipynb (unless otherwise specified).

__all__ = ['BOXSCORE_KWARGS']

# Cell

BOXSCORE_KWARGS = {
     'name' : 'table'
    ,'attrs' : {'class':'linescorebox'}
}